# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ahmetbugrakurnaz0@gmail.com
author_name: John Doe
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: smartcontract

